/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dc_iproject_sda;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        menuClass menuOptions = new menuClass(){};
        menuOptions.mainMenu();
    }
}