/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.src.test.java.dc_project_sda_;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        menuClassTest menuTest = new menuClassTest();
        menuTest.testAddingTaskCorrectedIntoArrayList();
    }
}
